replicaCount: 1

image:
  repository: traefik/whoami
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: "my-traefik"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod  # ðŸ‘ˆ must be indented under annotations
  tls:
    - hosts:
        - whoami.dklair.io
      secretName: whoami-tls
  hosts:
    - host: whoami.dklair.io
      paths:
        - path: /
          pathType: ImplementationSpecific
