replicaCount: 1

image:
  repository: traefik/whoami
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: "my-traefik"
  annotations: {}
  tls:
    - hosts:
        - whoami.dklair.io
      secretName: whoami-tls
  hosts:
    - host: whoami.dklair.io
      paths:
        - path: /
          pathType: ImplementationSpecific
